"""Orders Table Updated

Revision ID: 53f04bc0f39b
Revises: 63337da33810
Create Date: 2026-06-27 15:25:07.465631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f04bc0f39b'
down_revision: Union[str, None] = '63337da33810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('razorpay_order_id', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('razorpay_payment_id', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('razorpay_signature', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'razorpay_signature')
    op.drop_column('orders', 'razorpay_payment_id')
    op.drop_column('orders', 'razorpay_order_id')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
