"""deletion flag in user

Revision ID: da7c2d089bb5
Revises: a3c6294ac33c
Create Date: 2026-06-17 11:59:50.625346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7c2d089bb5'
down_revision: Union[str, None] = 'a3c6294ac33c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('isDeleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'isDeleted')
    # ### end Alembic commands ###
